spring.application.name=spring-layered-template
spring.profiles.default=local

server.servlet.context-path=/api/v1
server.error.include-message=never
server.error.include-stacktrace=never

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

app.jwt.access-token-minutes=15
app.jwt.refresh-token-days=7
app.security.enabled=true
